name: Build and Test Story Summary Package

on:
  push:
    branches:
      - main
    tags:
      - "**"
  workflow_dispatch:
  pull_request:

permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  test:
    name: Run Tests with pytest
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/huggingface
            ~/nltk_data
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml') }}

      - name: Install dependencies
        run: pip install -e .[dev]

      - name: Lint with ruff
        run: ruff check --output-format=github .

      - name: Run Tests
        run: pytest

  build_wheel:
    name: Build Python Package
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build Package
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/story_summary-*.whl
            dist/story_summary-*.tar.gz
